"""
Revision ID: c3a3f7091608
Revises: 6877dbb04610
Create Date: 2025-08-09 14:04:44.031209
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a3f7091608'
down_revision: Union[str, None] = '6877dbb04610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('Recommended', 'Diet', 'Beauty', 'Health', name='article_category_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('meals', 'meal_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Morning', 'Lunch', 'Dinner', 'Snack', name='meal_type_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'meal_type',
               existing_type=sa.Enum('Morning', 'Lunch', 'Dinner', 'Snack', name='meal_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('articles', 'category',
               existing_type=sa.Enum('Recommended', 'Diet', 'Beauty', 'Health', name='article_category_enum', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


